// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  headline: dynamic(() => import("./Headline")),
  hero: dynamic(() => import("./Hero")),
  image_text_card: dynamic(() => import("./ImageTextCard")),
  intro_text: dynamic(() => import("./IntroText")),
};
