// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  country_map: dynamic(() => import("./CountryMap")),
  dropdown_content: dynamic(() => import("./DropdownContent")),
  headline: dynamic(() => import("./Headline")),
  hero: dynamic(() => import("./Hero")),
  image_text_card: dynamic(() => import("./ImageTextCard")),
  intro_text: dynamic(() => import("./IntroText")),
};
